### ISSUE TITLE
iframes persist when following external links

### ISSUE THREAD

**Issue by SarenCurrie** [ausesa/ausesa.github.com#23]
![capture](https://cloud.githubusercontent.com/assets/8222891/6544054/1ac2789a-c5a0-11e4-8e70-c927d3a71b98.PNG)

**Comment by SarenCurrie** [comment]
I don't think this would be possible to fix without adding javascript. Probably best just to leave it to now.

**Comment by phoglenix** [comment]
https://stackoverflow.com/questions/4377324/force-iframe-links-in-embedded-google-doc-to-open-in-new-window
See last comment

**Comment by SarenCurrie** [comment]
Done.

**Comment by xShay** [comment]
Is this actually fixed? I can still reproduce this issue on sesa.org.nz.

I'm not sure if this is possible to fix simply using JS since iFrames have a same-origin policy.

**Comment by SarenCurrie** [comment]
What browser? Did you clear your cache? It works for me in safari.

**Comment by SarenCurrie** [comment]
Update: firefox: working
safari: working
chrome: still broken

**Comment by SarenCurrie** [comment]
Update again: safari, firefox, chrome are all working (forgot to clear my cache). IE is an unknown quantity...

**Comment by SarenCurrie** [comment]
Working on all modern browsers. Broken in IE 11.
Status: won't fix.
