### ISSUE TITLE
Make 'Student Links' an actual page on the website

### ISSUE THREAD

**Issue by ChineseElectricPanda** [ausesa/ausesa.github.com#34]
Currently it's just a link to a Google doc

**Comment by phoglenix** [comment]
FYI there's a semi-good reason for this being a google doc -- it allows for access restriction to @aucklanduni.ac.nz accounts only. Might be worthwhile to keep or just embed it in a page.
Links that don't need to be hidden from non-students could go elsewhere.

**Comment by itemic** [comment]
The link isn't currently access restricted (view only even when logged out) and IIRC hasn't been for at least a couple of years. Some of the links in the doc are access restricted however.

**Comment by phoglenix** [comment]
Ok, so probably worth just making it a regular page then and restricting the links if necessary
