### ISSUE TITLE
Properly migrate to the new sesa.nz

### ISSUE THREAD

**Issue by ChineseElectricPanda** [ausesa/ausesa.github.com#39]
Currently it's just an iframe pointing to the github pages page. Also need to add the favicon to the new site.

Also update all references on promotional material to refer to sesa.nz instead of sesa.org.nz.

**Comment by SarenCurrie** [comment]
Are you sure this is something worth doing? Given the email addresses are currently at the old domain and you’d have to set up a new google apps account to create new ones. Maybe just set up an alias in the new domain’s DNS to the old domain.

**Comment by ChineseElectricPanda** [comment]
During our meeting we decided to keep sesa.org.nz as the main site and have sesa.nz just redirect for now. It's probably worth keeping the sesa.nz around just in case we find a use for it one day.
