### ISSUE TITLE
Teqnique logo is super ugly

### ISSUE THREAD

**Issue by SarenCurrie** [ausesa/ausesa.github.com#40]
Looks like someone just traced a png, maybe ask them for a better logo.

What it looks like
![screen shot 2017-04-24 at 2 48 38 pm](https://cloud.githubusercontent.com/assets/8222891/25320681/39bed168-28fd-11e7-8583-85ef8362d5c7.png)
What it should look like
![screen shot 2017-04-24 at 2 48 52 pm](https://cloud.githubusercontent.com/assets/8222891/25320680/39be9ee6-28fd-11e7-85dc-e3115666b625.png)

**Comment by paregos** [comment]
Im going to put a white one in for the sake of contrast.

**Comment by SarenCurrie** [comment]
Much better.
