### ISSUE TITLE
iframe on the sesa.org.nz/join/ page cannot load

### ISSUE THREAD

**Issue by IanvsPoplicola** [ausesa/ausesa.github.com#42]
Loading the [http://sesa.org.nz/join/](http://sesa.org.nz/join/) page results in the following message, and does not display the sign-up form.
`Load denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://docs.google.com/forms/d/e/1FAIpQLScCpTYzaQVm_Q4o0QErtRu5t-hBUdk4t7_6rtlYu0eY9Z2r8A/viewform?embedded%3Dtrue&followup=https://docs.google.com/forms/d/e/1FAIpQLScCpTYzaQVm_Q4o0QErtRu5t-hBUdk4t7_6rtlYu0eY9Z2r8A/viewform?embedded%3Dtrue&ltmpl=forms does not permit framing.`

**Comment by phoglenix** [comment]
It seems that it loads only when you're signed in to a Google account?

**Comment by SarenCurrie** [comment]
That’s a fairly annoying dependency.

**Comment by phoglenix** [comment]
Don't know if it's a dependency. A quick search suggests other people have
seen and solved this problem.

**Comment by phoglenix** [comment]
Actually looks like it's trying to load the Google login page which of
course doesn't want to load inside a frame. Is the form set to require
logged in users now?

**Comment by paregos** [comment]
The form looks like its requiring logged in users because it has the only allow one sign up per user option enabled.

![image](https://cloud.githubusercontent.com/assets/14084810/25647868/fd622584-3019-11e7-94b8-e3507d3fc701.png)

We could disable it, I dont think people will intentionally sign up more than once.

**Comment by phoglenix** [comment]
Seems sensible and easy

**Comment by paregos** [comment]
I've changed it, @IanvsPoplicola can you check if it is ok for you now?

**Comment by phoglenix** [comment]
Working now for me.
