### ISSUE TITLE
Pages cannot use full width

### ISSUE THREAD

**Issue by mjakeman** [ausesa/ausesa.github.com#81]
Various pages like opportunities and the join form are not using the entire page width

![image](https://user-images.githubusercontent.com/12368711/153806228-99239974-c16e-48c2-8241-96807fb82564.png)

**Comment by HiruNya** [comment]
This patch fixes most of my problems with that skinny width container and works on all of the pages(?)
```diff
diff --git a/css/style.scss b/css/style.scss
index edba1ad..2ffba34 100644
--- a/css/style.scss
+++ b/css/style.scss
@@ -640,6 +640,7 @@ a:hover {
     flex-direction: column;
     align-content: center;
     padding: 0 $margin-large-display;
+    width: 100%;
 
     @media #{$large-display} {
       padding: 0;
```

**Comment by mjakeman** [comment]
Hmm, I managed to fix it by removing one of the `display: flex` containers which was forcing everything into a column layout (See #83)
